import { render } from '@testing-library/react'
import Gallery from './Gallery.jsx'

it('Should render multiple pokemon', () => {
  const { container } = render(<Gallery galleryItems={[
    {
      _id: '5ff4fb7cd89993a89cc65481',
      pokemon: 'primeape',
      id: 63,
      species_id: 57,
      height: 10,
      weight: 320,
      base_experience: 159,
      type_1: 'fighting',
      type_2: 'NA',
      attack: 105,
      defense: 60,
      hp: 65,
      special_attack: 60,
      special_defense: 70,
      speed: 95,
      ability_1: 'vital-spirit',
      ability_2: 'anger-point',
      ability_hidden: 'defiant',
      color_1: '#C03028',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'ground',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png',
      generation_id: 1,
      evolves_from_species_id: '56',
      evolution_chain_id: 24,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'primeape',
      pokedex: 'http://www.pokemon.com/us/pokedex/primeape'
    },
    {
      _id: '5ff4fb7cd89993a89cc65485',
      pokemon: 'poliwhirl',
      id: 67,
      species_id: 61,
      height: 10,
      weight: 200,
      base_experience: 135,
      type_1: 'water',
      type_2: 'NA',
      attack: 65,
      defense: 65,
      hp: 65,
      special_attack: 50,
      special_defense: 50,
      speed: 90,
      ability_1: 'water-absorb',
      ability_2: 'damp',
      ability_hidden: 'swift-swim',
      color_1: '#6890F0',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'water1',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png',
      generation_id: 1,
      evolves_from_species_id: '60',
      evolution_chain_id: 26,
      shape_id: 12,
      shape: 'humanoid',
      pokebase: 'poliwhirl',
      pokedex: 'http://www.pokemon.com/us/pokedex/poliwhirl'
    },
    {
      _id: '5ff4fb7cd89993a89cc65488',
      pokemon: 'abra',
      id: 69,
      species_id: 63,
      height: 9,
      weight: 195,
      base_experience: 62,
      type_1: 'psychic',
      type_2: 'NA',
      attack: 20,
      defense: 15,
      hp: 25,
      special_attack: 105,
      special_defense: 55,
      speed: 90,
      ability_1: 'synchronize',
      ability_2: 'inner-focus',
      ability_hidden: 'magic-guard',
      color_1: '#F85888',
      color_2: 'NA',
      color_f: 'NA',
      egg_group_1: 'humanshape',
      egg_group_2: 'NA',
      url_image: 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png',
      generation_id: 1,
      evolves_from_species_id: 'NA',
      evolution_chain_id: 27,
      shape_id: 6,
      shape: 'upright',
      pokebase: 'abra',
      pokedex: 'http://www.pokemon.com/us/pokedex/abra'
    }
  ]} />)

  expect(container).toMatchSnapshot()
})